# 导航栏设置
navbar:
  blog_title: 李福毅
  menu:
    - { key: '首页', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: '归档', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: '分类', link: '/categories/', icon: 'iconfont icon-category-fill' }
    - { key: '标签', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: '关于我', link: '/about/', icon: 'iconfont icon-user-fill', name: '联系我' }
    - { key: '友情链接', link: '/links/', icon: 'iconfont icon-link-fill' }

# 懒加载配置
lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2

# 全局字体配置
font:  # 主题字体配置
  font_size: 16px        # 全局字号
  font_family: cursive   # 全局字体族
  code_font_size: 85%    # 代码的字号

# 文章设置
post:
  meta:
    author:  # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
      enable: false
    date:  # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
      enable: true
      format: "yyyy年MM月DD日 hh点"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: false
      format: "{} 分钟"
    views:  # 阅读次数
      enable: false
      source: "leancloud"  # 统计数据来源，可选：leancloud | busuanzi   注意不蒜子会间歇抽风
      format: "{} 次"

# 主页设置
index:
  slogan:
    enable: true
    text: 我有一壶酒，足以慰风尘。

# 友情链接
links:
  items:
    - {
      title: '郭守敬',
      intro: '郭守敬的博客',
      link: 'https://corgiboy.com/',
      avatar: '/img/avatar.png'
    }
  default_avatar: /img/avatar.png

# 主题模式
dark_mode:
  enable: true
  # auto / light / dark
  default: light

# 打字机特效设置
fun_features:
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 70 # 打印速度
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果

footer:
  content: "李福毅的博客"
